# Generated by Django 2.2.5 on 2021-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Employee First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Employee Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('city', models.CharField(max_length=35)),
            ],
        ),
    ]
